WITH TOTAL_BOOK AS(
    SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = 2022 and MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
)

SELECT AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY,
    SUM(TOTAL_BOOK_PRICE) AS TOTAL_SALES
FROM (SELECT TOTAL_SALES * PRICE AS TOTAL_BOOK_PRICE, BOOK_ID
     FROM TOTAL_BOOK NATURAL JOIN BOOK) AS TBP 
     NATURAL JOIN BOOK
     NATURAL JOIN AUTHOR
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC