-- 코드를 작성해주세요
SELECT ID,
    IFNULL(CHILD_COUNT,0) AS CHILD_COUNT
FROM ECOLI_DATA AS E LEFT JOIN (SELECT COUNT(*) AS CHILD_COUNT,PARENT_ID FROM ECOLI_DATA GROUP BY PARENT_ID ) AS A ON E.ID = A.PARENT_ID
ORDER BY ID