WITH SALES AS (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
)
SELECT PRODUCT_CODE, (PRICE * SALES_AMOUNT) AS SALES
FROM PRODUCT NATURAL JOIN SALES
ORDER BY SALES DESC, PRODUCT_CODE ASC