WITH CAR_SALE AS (
    SELECT CAR_TYPE, CAST(REPLACE(DISCOUNT_RATE,'%',"") AS UNSIGNED) AS DISCOUNT
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE IN ('세단','SUV') 
)
SELECT CAR_ID,
    CAR_TYPE,
    CAST((DAILY_FEE * (1 - DISCOUNT / 100.0)) * 30 AS UNSIGNED) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C NATURAL JOIN CAR_SALE AS S
WHERE NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID = C.CAR_ID
        AND START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    ) 
    AND (DAILY_FEE * (1 - DISCOUNT / 100.0)) * 30 BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC