-- 코드를 입력하세요
SELECT FOOD_TYPE,
    REST_ID,
    REST_NAME,
    FAVORITES
FROM REST_INFO NATURAL JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS BEST FROM REST_INFO GROUP BY FOOD_TYPE) AS A
WHERE BEST = FAVORITES
ORDER BY FOOD_TYPE DESC