-- 코드를 작성해주세요
SELECT ID,
    CASE WHEN ECOLI_SIZE = 1
    THEN 'CRITICAL'
    WHEN ECOLI_SIZE = 2
    THEN 'HIGH'
    WHEN ECOLI_SIZE = 3
    THEN 'MEDIUM'
    WHEN ECOLI_SIZE = 4
    THEN 'LOW'
    END
    AS COLONY_NAME
FROM ECOLI_DATA NATURAL JOIN (SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS ECOLI_SIZE FROM ECOLI_DATA) AS A
ORDER BY ID