-- 코드를 입력하세요
SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_OUTS AS O
WHERE EXISTS (SELECT 1 FROM ANIMAL_INS AS I WHERE O.ANIMAL_ID = I.ANIMAL_ID AND I.SEX_UPON_INTAKE LIKE 'Intact%')
AND (O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR O.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY ANIMAL_ID
