WITH YEAR_TBL AS (
    SELECT DATE_FORMAT(SALES_DATE,"%Y") AS YEAR, DATE_FORMAT(SALES_DATE,"%m") AS MONTH, ONLINE_SALE_ID
    FROM ONLINE_SALE
)
SELECT YEAR,MONTH,GENDER, COUNT(DISTINCT USER_ID) AS USERS
FROM USER_INFO NATURAL JOIN ONLINE_SALE NATURAL JOIN YEAR_TBL
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH,GENDER
ORDER BY YEAR, MONTH,GENDER