-- 코드를 작성해주세요
# SELECT FISH_COUNT,
#     FISH_NAME
# FROM FISH_NAME_INFO NATURAL JOIN (SELECT FISH_TYPE, count(*) AS FISH_COUNT
#                                   FROM FISH_INFO
#                                   GROUP BY FISH_TYPE) AS FISH_CNT_TBL
# ORDER BY FISH_COUNT DESC

SELECT COUNT(*) AS FISH_COUNT,
    FISH_NAME
FROM FISH_NAME_INFO NATURAL JOIN FISH_INFO AS FI
GROUP BY FISH_TYPE, FISH_NAME
ORDER BY FISH_COUNT DESC