-- 코드를 입력하세요
SELECT YEAR,
    MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) PUCHASED_RATIO
FROM (SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID FROM ONLINE_SALE) AS A NATURAL JOIN (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021) AS B
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH