WITH RECURSIVE GENERATION_TBL
AS ( 
    -- Non-Recursive 문장( 첫번째 루프에서만 실행됨 )
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    -- Recursive 문장(읽어 올 때마다 행의 위치가 기억되어 다음번 읽어 올 때 다음 행으로 이동함)
    SELECT E.ID, GENERATION + 1 AS GENERATION
    FROM GENERATION_TBL AS G JOIN ECOLI_DATA AS E ON E.PARENT_ID = G.ID
)
SELECT COUNT(*) AS COUNT, 
    GENERATION
FROM ECOLI_DATA AS E NATURAL JOIN GENERATION_TBL AS G
WHERE NOT EXISTS (SELECT 1
                 FROM ECOLI_DATA AS E2
                 WHERE E.ID = E2.PARENT_ID)
GROUP BY GENERATION
ORDER BY GENERATION