-- 코드를 입력하세요
SELECT CAR_ID,
    CASE  
    WHEN (NOT EXISTS (SELECT 1 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h WHERE h.CAR_ID = i.CAR_ID AND '2022-10-16' BETWEEN START_DATE AND END_DATE)) 
    THEN '대여 가능'
    ELSE '대여중'
    END
    AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS i
GROUP BY CAR_ID
ORDER BY CAR_ID DESC