-- 코드를 입력하세요
SELECT PRODUCT_ID,
    PRODUCT_NAME,
    SUM(AMOUNT) * PRICE AS TOTAL_SALES
FROM FOOD_ORDER NATURAL JOIN FOOD_PRODUCT
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID