WITH RECURSIVE HOUR_BASE AS (
    SELECT 0 AS N
    UNION ALL
    SELECT N + 1
    FROM HOUR_BASE
    WHERE N < 23           -- <= 23면 24가 생깁니다!
)
SELECT N AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM HOUR_BASE LEFT JOIN ANIMAL_OUTS ON N = HOUR(DATETIME)
GROUP BY N
ORDER BY HOUR