-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE NATURAL JOIN REST_REVIEW
WHERE MEMBER_ID IN (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID HAVING count(*) = (SELECT MAX(cnt) FROM (SELECT COUNT(*) AS cnt FROM REST_REVIEW GROUP BY MEMBER_ID) AS A))
ORDER BY REVIEW_DATE, REVIEW_TEXT 