WITH YEAR_MAX_COLONY AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT 
    YEAR,
    (MAX_COLONY - SIZE_OF_COLONY) AS YEAR_DEV, 
    ID
FROM ECOLI_DATA JOIN YEAR_MAX_COLONY ON YEAR(DIFFERENTIATION_DATE) = YEAR
ORDER BY YEAR, YEAR_DEV