SELECT B.TITLE AS TITLE, 
    R.BOARD_ID AS BOARD_ID,
    R.REPLY_ID AS REPLY_ID,
    R.WRITER_ID AS WRITER_ID,
    R.CONTENTS AS CONTENTS,
    DATE_FORMAT(R.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS B JOIN USED_GOODS_REPLY AS R ON B.BOARD_ID = R.BOARD_ID
WHERE DATE(B.CREATED_DATE) BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY CREATED_DATE, TITLE