-- 코드를 입력하세요
SELECT CATEGORY,
    SUM(S) AS TOTAL_SALES
FROM BOOK NATURAL JOIN (SELECT BOOK_ID, SUM(SALES) AS S FROM BOOK_SALES WHERE SALES_DATE LIKE '2022-01%' GROUP BY BOOK_ID ) AS A
GROUP BY CATEGORY
ORDER BY CATEGORY 
