SELECT COUNT(*) AS FISH_COUNT,  
    MAX_LENGTH,
    FISH_TYPE
FROM FISH_INFO NATURAL JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS MAX_LENGTH_TBL
GROUP BY FISH_TYPE 
HAVING AVG(IFNULL(`LENGTH`,10)) >= 33
ORDER BY FISH_TYPE