# WITH RANK AS (
#     SELECT 'FE' AS RANK, (SELECT sum(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') AS CODE
#     FROM SKILLCODES
#     UNION
#     SELECT 'PY' AS RANK, (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AS CODE
#     FROM SKILLCODES
#     UNION
#     SELECT 'CP' AS RANK, (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') AS CODE
#     FROM SKILLCODES
# )
WITH `RANK` AS (
    SELECT (SELECT sum(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') AS FE,
    (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AS PY, 
    (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') AS CP
    FROM SKILLCODES LIMIT 1
)

SELECT
GRADE, ID, EMAIL
FROM DEVELOPERS NATURAL JOIN 
(SELECT CASE 
WHEN (D.SKILL_CODE & R.PY) > 0 AND (D.SKILL_CODE & R.FE) > 0 THEN 'A'
WHEN (D.SKILL_CODE & R.CP) > 0 THEN 'B'
WHEN (D.SKILL_CODE & R.FE) > 0 THEN 'C'
END AS GRADE,ID
FROM DEVELOPERS AS D, `RANK` AS R) AS F
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID