-- 코드를 입력하세요
SELECT PRICE_GROUP,
    COUNT(*) AS PRODUCTS
FROM PRODUCT NATURAL JOIN (SELECT PRODUCT_ID, FLOOR(PRICE / 10000) * 10000 AS PRICE_GROUP FROM PRODUCT) AS A
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP

# SELECT * FROM PRODUCT ORDER BY PRICE